chai_menu = [
    {
        "id": 1,
        "name": "Masala Chai",
        "category": "Chai",
        "price": 25.0,
        "description": "Traditional Indian tea brewed with aromatic spices like cardamom, ginger, cloves, and cinnamon.",
        "available": True,
    },
    {
        "id": 2,
        "name": "Adrak Chai",
        "category": "Chai",
        "price": 25.0,
        "description": "Fresh ginger-infused strong tea, perfect for a refreshing boost.",
        "available": True,
    },
    {
        "id": 3,
        "name": "Elaichi Chai",
        "category": "Chai",
        "price": 30.0,
        "description": "Fragrant tea infused with freshly crushed green cardamoms.",
        "available": True,
    },
    {
        "id": 4,
        "name": "Kesar Chai",
        "category": "Chai",
        "price": 50.0,
        "description": "Royal saffron-flavored tea served with rich milk and subtle cardamom.",
        "available": True,
    },
    {
        "id": 5,
        "name": "Kulhad Chai",
        "category": "Chai",
        "price": 35.0,
        "description": "Earthy and smoky flavored tea served hot in a traditional unglazed clay cup.",
        "available": True,
    },
    {
        "id": 6,
        "name": "Sulaimani Chai",
        "category": "Black Tea",
        "price": 20.0,
        "description": "Traditional spiced black tea with a dash of lemon and mint, without milk.",
        "available": True,
    },
    {
        "id": 7,
        "name": "Kashmiri Kahwa",
        "category": "Green Tea",
        "price": 60.0,
        "description": "Exotic green tea brewed with saffron strands, whole spices, and slivered almonds.",
        "available": False,
    },
    {
        "id": 8,
        "name": "Tulsi Herbal Chai",
        "category": "Herbal Tea",
        "price": 30.0,
        "description": "Soothing holy basil tea with wellness herbs and natural honey.",
        "available": True,
    },
    {
        "id": 9,
        "name": "Cutting Chai",
        "category": "Chai",
        "price": 15.0,
        "description": "Mumbai-style half-cup strong, sweet, and milky tea.",
        "available": True,
    },
    {
        "id": 10,
        "name": "Iced Lemon Chai",
        "category": "Iced Tea",
        "price": 45.0,
        "description": "Chilled black tea with fresh lemon juice and mint leaves over ice.",
        "available": True,
    },
    {
        "id": 11,
        "name": "Samosa",
        "category": "Snacks",
        "price": 20.0,
        "description": "Crispy golden fried pastry stuffed with spiced potato and pea filling.",
        "available": True,
    },
    {
        "id": 12,
        "name": "Kanda Bhajiya",
        "category": "Snacks",
        "price": 40.0,
        "description": "Crispy onion fritters seasoned with carom seeds and green chilies.",
        "available": True,
    },
    {
        "id": 13,
        "name": "Bun Maska",
        "category": "Bakery",
        "price": 35.0,
        "description": "Soft warm bun generously smeared with butter, classic accompaniment to chai.",
        "available": True,
    },
    {
        "id": 14,
        "name": "Osmania Biscuits",
        "category": "Bakery",
        "price": 15.0,
        "description": "Traditional sweet and slightly salty melt-in-mouth tea biscuits.",
        "available": True,
    },
    {
        "id": 15,
        "name": "Paneer Pakoda",
        "category": "Snacks",
        "price": 60.0,
        "description": "Tender cottage cheese cubes dipped in spiced gram flour batter and deep-fried.",
        "available": False,
    },
    {
        "id": 16,
        "name": "Poha",
        "category": "Breakfast",
        "price": 45.0,
        "description": "Flattened rice tempered with mustard seeds, curry leaves, peanuts, and turmeric.",
        "available": True,
    },
    {
        "id": 17,
        "name": "Vada Pav",
        "category": "Snacks",
        "price": 25.0,
        "description": "Spicy potato dumpling stuffed inside a soft bun with dry garlic chutney.",
        "available": True,
    },
    {
        "id": 18,
        "name": "Chai Rusk (Toas)",
        "category": "Bakery",
        "price": 15.0,
        "description": "Double-baked crunchy cardamom flavored bread toasts for tea dipping.",
        "available": True,
    },
    {
        "id": 19,
        "name": "Mirchi Bajji",
        "category": "Snacks",
        "price": 30.0,
        "description": "Deep-fried batter-coated large green chillies stuffed with tangy spices.",
        "available": True,
    },
    {
        "id": 20,
        "name": "Matthi",
        "category": "Snacks",
        "price": 20.0,
        "description": "Flaky and crispy spiced savory flour crackers flavored with ajwain.",
        "available": True,
    },
]
